# Site settings
title: Charles Troupin
email: ctroupin@protonmail.com
url: https://ctroupin.github.io
description: "Turning ocean data into stories"
keywords: "data analyst, engineering, oceanography, ocean science, numerical modelling"
skills: "Engineer • Data analyst • Oceanographer • Ultra-Runner"
meta_author: Troupin Charles
credits: 'Style based on <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Jekyll theme</a> by jeromelachaud. Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
address:
  - line: "Verviers, Liège"
  - line: "Belgium"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E7E7E7
  primary-rgb: "254,179,0" #"128,179,255"
  secondary: 313131
  secondary-dark: 1B1B1B #A2122F
  link: 1483d3

# Footer settings
footer:
  copyright: Charles Troupin
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ctroupin/
  - title: linkedin
    url: https://www.linkedin.com/in/charlestroupin


socialpic:
  - title: twitter
    url: https://twitter.com/CharlesTroupin
  - title: flickr
    url: https://www.flickr.com/photos/sharlo1982/
  - title: 500px
    url: https://500px.com/charlestroupin
  - title: vimeo
    url: https://vimeo.com/user40792705

academic:
  - title: orcid
    url: http://orcid.org/0000-0002-0265-1021
  - title: researchgate
    url: https://www.researchgate.net/profile/Charles_Troupin

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  posts:
    output: true
    permalink: /posts/:path/
  projects:
    output: true
    permalink: /projects/:path/
  running:
    output: true
    permalink: /running/:path/
  maps:
    output: true
    permalink: /maps/:path/
  leaflet:
    output: true
    permalink: /leaflet/:path/


# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'trac'


highlighter: rouge

plugins:
  - rouge

plugins_dir:
  - jekyll-scholar

page_data:
  - title: "Publications"
    id: "publications"
    url: "publications"

  - title: "Sport"
    id: "sports"
    url: "sports"

  - title: "Photography"
    id: "photography"
    url: "photography"


plugins: ['jekyll/scholar']

scholar:
  style: _layouts/copernicus-publications
  locale: en

  sort_by: 'year'
  order: ascending

  source: ./CV
  bibliography: ./CV/Troupin_publi.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  query: "@*"

  bibtex_filters: latex
