# Site settings
title: C. Troupin
email: charles.troupin@gmail.com
url: https:www.ctroupin.github.io
description: "I try to turn data into stories"
keywords: "data analyst, engineering, oceanography, ocean science, numerical modelling"
skills: "Engineer in Physics - Data analyst - Oceanographer - Ultra-runner"
meta_author: Troupin Charlres

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FEB300
  primary-rgb: "254,179,0" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Charles Troupin
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ctroupin/
  - title: twitter
    url: https://twitter.com/CharlesTroupin
  - title: linkedin
    url: https://www.linkedin.com/in/charlestroupin

socialpic:
  - title: flickr
    url: https://www.flickr.com/photos/sharlo1982/
  - title: 500px
    url: https://500px.com/charlestroupin
  - title: vimeo
    url: https://vimeo.com/charlestroupin

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  posts:
    output: true
    permalink: /posts/:path/


# Build settings
markdown: kramdown
permalink: pretty
