#!/bin/bash
# Compile the CV (tex file) and the corresponding bibliographies
#

XELATEX='/usr/local/texlive/2017/bin/x86_64-linux/xelatex'
PDFLATEX='/usr/bin/pdflatex'
BIBTEX='/usr/bin/bibtex'
input='Ctroupin_CVacademic.tex'
inputref="publicationList.tex"
${XELATEX} ${input}
${BIBTEX} article.aux
${BIBTEX} conference.aux
${BIBTEX} incollection.aux
${XELATEX} ${input}

${XELATEX} ${inputref}
${BIBTEX} $(basename "${inputref}" ".tex")".aux"
${XELATEX} ${inputref}
