#!/bin/bash
# Compile the CV (tex file) and the corresponding bibliographies
#

XELATEX='/usr/bin/xelatex'
PDFLATEX='/usr/bin/pdflatex'
BIBTEX='/usr/bin/bibtex'
input='Ctroupin_CVacademic.tex'
inputref="publicationList.tex"
${XELATEX} ${input}
${BIBTEX} article.aux
${BIBTEX} conference.aux
${BIBTEX} proceedings.aux
${BIBTEX} incollection.aux
${XELATEX} ${input}

${XELATEX} ${inputref}
${BIBTEX} $(basename "${inputref}" ".tex")".aux"
${XELATEX} ${inputref}
