#!/bin/bash
PDFLATEX='/usr/bin/pdflatex'
BIBTEX='/usr/bin/bibtex'
input='Ctroupin_CVacademic.tex'
${PDFLATEX} ${input}
${BIBTEX} article.aux
${BIBTEX} conference.aux
${BIBTEX} incollection.aux
${PDFLATEX} ${input}

